### ISSUE TITLE
Let's learn Blockchain

### ISSUE THREAD

**Issue by WonderEagle** [SoftwareVeteran/solana-wallet#4]
This is our first blockchain course.
Please feel free to share your knowledge and skills here.

**Comment by passionatedevfuture** [comment]
that is good

**Comment by WonderEagle** [comment]
It's too long.

**Comment by WonderEagle** [comment]
![T061LEKR8CR-U06C485855W-0b3c9260be1e-512](https://github.com/test2500/solana-wallet/assets/38038268/e440cb2f-e550-4bd2-9304-96fb4b873898)
